name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        channel: [stable, beta, dev]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Flutter action
        uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      - name: Run Tests
        run: |
          flutter pub get
          flutter format --dry-run --set-exit-if-changed .
          flutter analyze --no-pub
          flutter test --no-pub --coverage
      - name: Upload coverage to Codecov
        if: ${{ matrix.channel == 'stable' }}
        uses: codecov/codecov-action@v1
        with:
          file: coverage/lcov.info
